[0m09:54:50.429082 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D485170B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D46392540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D48F6A7B0>]}


============================== 09:54:50.437847 | 620c2f23-dd71-4ea9-84b8-bedbb145d1d5 ==============================
[0m09:54:50.437847 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m09:54:50.442900 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\Admin\\desktop\\data_build\\simple_dbt_project\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m09:54:50.939942 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '620c2f23-dd71-4ea9-84b8-bedbb145d1d5', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D490A95B0>]}
[0m09:54:51.081122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '620c2f23-dd71-4ea9-84b8-bedbb145d1d5', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D48BB33E0>]}
[0m09:54:51.088821 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m09:54:51.111040 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m09:54:51.116643 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m09:54:51.118646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '620c2f23-dd71-4ea9-84b8-bedbb145d1d5', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D48BE6A50>]}
[0m09:54:52.983651 [error] [MainThread]: Encountered an error:
Compilation Error
  dbt found two models with the name "customer_orders".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for ref("customer_orders").
  
  To fix this, change the name of one of these resources:
  - model.simple_dbt_project.customer_orders (models\simple_dbt_project\mart\customer_orders.sql)
  - model.simple_dbt_project.customer_orders (models\mart\customer_orders.sql)
[0m09:54:52.983651 [debug] [MainThread]: Command `dbt seed` failed at 09:54:52.983651 after 3.00 seconds
[0m09:54:52.983651 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D4863B500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D4938E7B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D46D59730>]}
[0m09:54:52.993383 [debug] [MainThread]: Flushing usage events
[0m09:54:54.478208 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:58:22.853250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B369FAA8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3673D2420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B369DB6AB0>]}


============================== 09:58:22.860288 | 3d8cd5f8-aa20-4ef1-8da2-5e7a34948e90 ==============================
[0m09:58:22.860288 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m09:58:22.866103 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\Admin\\desktop\\data_build\\simple_dbt_project\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:58:23.224078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '3d8cd5f8-aa20-4ef1-8da2-5e7a34948e90', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B36A334410>]}
[0m09:58:23.323160 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '3d8cd5f8-aa20-4ef1-8da2-5e7a34948e90', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B369A1D400>]}
[0m09:58:23.323160 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m09:58:23.346295 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m09:58:23.348297 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m09:58:23.349296 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '3d8cd5f8-aa20-4ef1-8da2-5e7a34948e90', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B36A337AD0>]}
[0m09:58:25.097105 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m09:58:25.104843 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m09:58:25.356794 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\simple_dbt_project\staging\stg_customer.sql) depends on a node named 'customer' which was not found
[0m09:58:25.356794 [debug] [MainThread]: Command `dbt seed` failed at 09:58:25.356794 after 2.81 seconds
[0m09:58:25.356794 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3695DDCA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B367E13350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B36A3AA900>]}
[0m09:58:25.356794 [debug] [MainThread]: Flushing usage events
[0m09:58:26.740294 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:04:38.336827 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B29B6A000>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B29ADC290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2BDBC2C0>]}


============================== 10:04:38.336827 | d10a7ca4-1e66-4b37-9177-7f0f30f1492d ==============================
[0m10:04:38.336827 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m10:04:38.347295 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'C:\\Users\\Admin\\desktop\\data_build\\simple_dbt_project\\logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:04:38.691908 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd10a7ca4-1e66-4b37-9177-7f0f30f1492d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2BE3C2F0>]}
[0m10:04:38.791107 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd10a7ca4-1e66-4b37-9177-7f0f30f1492d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2C996ED0>]}
[0m10:04:38.807531 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m10:04:38.807531 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m10:04:38.826796 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m10:04:38.828590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'd10a7ca4-1e66-4b37-9177-7f0f30f1492d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2C971FD0>]}
[0m10:04:40.547045 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'customer_orders.sql' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:04:40.549206 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:04:40.552594 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:04:40.839787 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\simple_dbt_project\staging\stg_customer.sql) depends on a node named 'customer' which was not found
[0m10:04:40.841840 [debug] [MainThread]: Command `dbt seed` failed at 10:04:40.841840 after 2.81 seconds
[0m10:04:40.841840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2C4409B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2DE14B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026B2A5EB680>]}
[0m10:04:40.841840 [debug] [MainThread]: Flushing usage events
[0m10:04:42.124583 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:06:04.947395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA69D3020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA6D32E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA676DD60>]}


============================== 10:06:04.947395 | 032cceda-56b3-40f1-9e6e-f4780b80ef0b ==============================
[0m10:06:04.947395 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m10:06:04.956488 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\Admin\\desktop\\data_build\\simple_dbt_project\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m10:06:05.331780 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '032cceda-56b3-40f1-9e6e-f4780b80ef0b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA72B59A0>]}
[0m10:06:05.429331 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '032cceda-56b3-40f1-9e6e-f4780b80ef0b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA72B5190>]}
[0m10:06:05.444957 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m10:06:05.447441 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m10:06:05.447441 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m10:06:05.463424 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '032cceda-56b3-40f1-9e6e-f4780b80ef0b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA7471700>]}
[0m10:06:07.181323 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'customer_orders.sql' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:06:07.194540 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:06:07.194540 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:06:07.444436 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\simple_dbt_project\staging\stg_customer.sql) depends on a node named 'customer' which was not found
[0m10:06:07.447097 [debug] [MainThread]: Command `dbt seed` failed at 10:06:07.446093 after 2.74 seconds
[0m10:06:07.448095 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA6EFF980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA8753D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DFA75AC410>]}
[0m10:06:07.448095 [debug] [MainThread]: Flushing usage events
[0m10:06:08.761288 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:10:59.938583 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC7DAF88C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC00462840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC00461580>]}


============================== 10:10:59.948918 | fec2f2ab-4f85-4ea4-96f6-b891dc133acd ==============================
[0m10:10:59.948918 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m10:10:59.950918 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\Admin\\desktop\\data_build\\simple_dbt_project\\logs', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:11:00.557535 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'fec2f2ab-4f85-4ea4-96f6-b891dc133acd', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC009920C0>]}
[0m10:11:00.691532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'fec2f2ab-4f85-4ea4-96f6-b891dc133acd', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC003F2000>]}
[0m10:11:00.694534 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m10:11:00.711538 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m10:11:00.714536 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m10:11:00.716533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'fec2f2ab-4f85-4ea4-96f6-b891dc133acd', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC00B2CC50>]}
[0m10:11:02.810543 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'customer_orders.sql' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:11:02.813545 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:11:02.816877 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\simple_dbt_project\mart\schema.yml'
[0m10:11:03.096097 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\simple_dbt_project\staging\stg_customer.sql) depends on a node named 'customer' which was not found
[0m10:11:03.098086 [debug] [MainThread]: Command `dbt run` failed at 10:11:03.098086 after 3.42 seconds
[0m10:11:03.100090 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC008E9BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC00C1D790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FC00C1E1B0>]}
[0m10:11:03.101086 [debug] [MainThread]: Flushing usage events
[0m10:11:04.489220 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:25:21.272865 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAEC3BEF60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAEC79C9E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAEA134C20>]}


============================== 11:25:21.279865 | d364e36b-18d7-4776-b8da-3f4ce5d1f828 ==============================
[0m11:25:21.279865 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m11:25:21.281867 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'log_path': 'C:\\Users\\Admin\\Desktop\\Data_build\\simple_dbt_project\\logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:25:21.654044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd364e36b-18d7-4776-b8da-3f4ce5d1f828', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAED0378C0>]}
[0m11:25:21.758805 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd364e36b-18d7-4776-b8da-3f4ce5d1f828', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAEA38BE00>]}
[0m11:25:21.761819 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m11:25:21.778160 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m11:25:21.780832 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m11:25:21.782818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'd364e36b-18d7-4776-b8da-3f4ce5d1f828', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAECF3AB10>]}
[0m11:25:23.465881 [error] [MainThread]: Encountered an error:
Compilation Error in model stg_state (models\staging\stg_state.sql)
  source() takes exactly two arguments (1 given)
[0m11:25:23.469881 [debug] [MainThread]: Command `dbt seed` failed at 11:25:23.469881 after 2.39 seconds
[0m11:25:23.470890 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAEC8CBEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAED37DFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FAED237DA0>]}
[0m11:25:23.472721 [debug] [MainThread]: Flushing usage events
[0m11:25:25.439550 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:31:09.276080 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203063AF890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203066D09E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020303B82690>]}


============================== 13:31:09.286578 | dec98784-9080-4615-9743-e72f926cdd9d ==============================
[0m13:31:09.286578 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m13:31:09.290458 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\Admin\\Desktop\\Data_build\\simple_dbt_project\\logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:31:09.703968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'dec98784-9080-4615-9743-e72f926cdd9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203069526F0>]}
[0m13:31:09.799941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'dec98784-9080-4615-9743-e72f926cdd9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020305E84980>]}
[0m13:31:09.799941 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m13:31:09.823437 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m13:31:09.832093 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m13:31:09.834049 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'dec98784-9080-4615-9743-e72f926cdd9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203069A6D50>]}
[0m13:31:11.526740 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\mart\schema.yml'
[0m13:31:11.541609 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\mart\schema.yml'
[0m13:31:12.011776 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\staging\stg_customer.sql) depends on a node named 'customer' which was not found
[0m13:31:12.016619 [debug] [MainThread]: Command `dbt seed` failed at 13:31:12.015614 after 3.08 seconds
[0m13:31:12.017617 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020306881BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203009F5280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020306C80410>]}
[0m13:31:12.018778 [debug] [MainThread]: Flushing usage events
[0m13:31:14.701945 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:32:46.977178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B024260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028378782780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000283786A4BF0>]}


============================== 13:32:46.985025 | ee11ac0d-d7fa-4c07-9cc7-a3806bfe59bc ==============================
[0m13:32:46.985025 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m13:32:46.988122 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\Admin\\Desktop\\Data_build\\simple_dbt_project\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:32:47.340394 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ee11ac0d-d7fa-4c07-9cc7-a3806bfe59bc', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B093CB0>]}
[0m13:32:47.440051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ee11ac0d-d7fa-4c07-9cc7-a3806bfe59bc', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B6399D0>]}
[0m13:32:47.442679 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m13:32:47.445319 [debug] [MainThread]: checksum: 4cfbbe2a671212f062e88a43cba5322b30b7e3e8e91b953aa4de249eeaade60f, vars: {}, profile: , target: , version: 1.9.0b2
[0m13:32:47.445319 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m13:32:47.460691 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'ee11ac0d-d7fa-4c07-9cc7-a3806bfe59bc', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B65B7D0>]}
[0m13:32:49.093486 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'order_status' in the 'models' section of file 'models\mart\schema.yml'
[0m13:32:49.095737 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'state_name' in the 'models' section of file 'models\mart\schema.yml'
[0m13:32:49.355661 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.simple_dbt_project.stg_customer' (models\staging\stg_customer.sql) depends on a node named 'customers' which was not found
[0m13:32:49.362883 [debug] [MainThread]: Command `dbt seed` failed at 13:32:49.362883 after 2.67 seconds
[0m13:32:49.362883 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B4801D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837B345070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002837C94FA70>]}
[0m13:32:49.365687 [debug] [MainThread]: Flushing usage events
[0m13:32:51.384312 [debug] [MainThread]: An error was encountered while trying to flush usage events
